
# Configuración de variables para la instalación
if(${CMAKE_HOST_SYSTEM} MATCHES "Linux")
    set(INSTALL_DIR "/usr/")
    set(SHARED_LIB LIBRARY)
elseif(${CMAKE_HOST_SYSTEM} MATCHES "Windows")
    set(INSTALL_DIR "")
    set(SHARED_LIB RUNTIME)
endif()

if(${CMAKE_HOST_SYSTEM} MATCHES "Windows")
    set(QT_LIBS ${QT_LIBRARIES})
    list(REMOVE_ITEM QT_LIBS  "optimized" )
    list(REMOVE_ITEM QT_LIBS  "debug" )
    foreach(next_ITEM ${QT_LIBS})
        string(REPLACE ".lib" ".dll"  QTLIB_  ${next_ITEM} )
        string(REPLACE "/lib/" "/bin/" QTLIB   ${QTLIB_} )
        list(APPEND QT_LIBS_TO_INSTALL ${QTLIB})
    endforeach()
    install(FILES ${QT_LIBS_TO_INSTALL} DESTINATION bin)
endif()


set(CPACK_PACKAGE_NAME "gdbase")
set(CPACK_PACKAGE_VENDOR "GfifDev S.A.S")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Falta")
set(CPACK_PACKAGE_VERSION "0.2.1")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "2")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "GfifDev")

macro(GDINSTALL_H DIR)
  foreach(VAL ${ARGN})
    if(${CMAKE_HOST_SYSTEM} MATCHES "Linux")
      install(FILES ${VAL} DESTINATION /usr/include/${DIR} )
    elseif(${CMAKE_HOST_SYSTEM} MATCHES "Windows")
      install(FILES ${VAL} DESTINATION include/${DIR} )
    endif()
  endforeach(VAL)
endmacro(GDINSTALL_H)
