set(CPACK_GENERATOR "DEB")

set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Sigifredo Escobar Gómez <sigifredo89@gmail.com.co>")
set(CPACK_DEBIAN_PACKAGE_VENDOR "IES")

set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Paquete de instalación de la plantilla")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
# set(CPACK_DEBIAN_PACKAGE_DEPENDS "dependencia1 (>= 2.1.1), dependencia2 (>= 1.0.0)")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "required")
set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_VERSION "${CMAKETEMPLATE_VERSION_FULL}")
set(CPACK_PACKAGE_VERSION_MAJOR "${CMAKETEMPLATE_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${CMAKETEMPLATE_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${CMAKETEMPLATE_VERSION_REVISION}")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_SOURCE_DIR}/config/scripts/postinst;${CMAKE_CURRENT_SOURCE_DIR}/config/scripts/postrm;${CMAKE_CURRENT_SOURCE_DIR}/config/scripts/prerm;")

include(CPack)
